# Hechos transito reportados por la SSC en CDMX 2018-2022

datos disponibles en:
- https://datos.cdmx.gob.mx/dataset/hechos-de-transito-reportados-por-ssc-base-ampliada-no-comparativa  

- https://datos.cdmx.gob.mx/dataset/hechos-de-transito-reportados-por-ssc-base-comparativa


- https://datos.cdmx.gob.mx/dataset/cicloestaciones-ecobici-nuevo-sistema/resource/5fbacfcc-f677-406c-9356-6ced541240fe

In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
import os

# Carga datos
Tenemos que combinar dos tablas porque hay errores en los años 2018-2019  en el CSV no_comparativa,  los cuales se  encuentran correctos en el CSV  comparataiva 2018-2019. Cabe mencionar que este es un Análisis únicamente exploratorio

In [4]:
os.chdir("..")

In [5]:
df_no_comparativa = pd.read_csv("./data/hechos_transito_nocomparativa.csv")

/tmp/ipykernel_65326/2969543974.py:1: DtypeWarning: Columns (4,17,18,19,21,22,49,53,58,59,60,61,62,64,66,67,68,69,70,71,83,84,85,87) have mixed types. Specify dtype option on import or set low_memory=False.
  df_no_comparativa = pd.read_csv("./data/hechos_transito_nocomparativa.csv")

In [9]:
df_no_comparativa.head(3)

,no_folio,fecha_evento,mes,hora,condicion,tipo_de_evento,coordenada_x,coordenada_y,punto_1,punto_2,...,pasajero_lesionado,motociclista_occiso,motociclista_lesionado,conductor_occiso,conductor_lesionado,diagnostico_occiso,diagnostico_lesionado,origen,rango_de_edades_menores_de_1_ano_occiso,matricula_unidad_medica
0,BJ/200406/03499,2020-04-06,abril,12:50:00,NaN,CHOQUE,19.368116,-99.142903,EJE 7 SUR,ANTILLAS,...,0.0,0.0,0.0,0.0,0.0,NaN,POLICONTUNDIDO,RADIO,NaN,NaN
1,C5/200406/05748,2020-04-06,abril,18:31:00,NaN,CHOQUE,19.301142,-99.115521,CALZ DEL HUESO,RANCHO COLORADO,...,0.0,0.0,1.0,0.0,0.0,NaN,POLICONTUNDIDO,911 CDMX,NaN,NaN
2,C5/200406/05802,2020-04-06,abril,18:39:00,NaN,CHOQUE,19.476843,-99.092207,EJE 5 NTE,AV GRAN CANAL DEL DESAGUE,...,0.0,0.0,1.0,0.0,0.0,NaN,HX BOCA,911 CDMX,NaN,NaN

In [4]:
df_no_comparativa.dtypes

no_folio                                    object
fecha_evento                                object
mes                                         object
hora                                        object
condicion                                   object
                                            ...
diagnostico_occiso                          object
diagnostico_lesionado                       object
origen                                      object
rango_de_edades_menores_de_1_ano_occiso    float64
matricula_unidad_medica                     object
Length: 88, dtype: object

In [7]:
df_comparativa = pd.read_csv("./data/hechos_transito_comparativa.csv")

In [10]:
df_comparativa.head()

,id,no_folio,fecha_evento,ano_evento,mes,hora,condicion,tipo_de_evento,coordenada_x,coordenada_y,...,identidad,unidad_medica_de_apoyo,lugar_del_deceso,trasladado_s_lesionado,hospital,dia,hora2,prioridad,observaciones,coordenada
0,0,906379,2019-01-01,2019,Enero,10:13,LESIONADO,ATROPELLADO,-99.143964,19.307892,...,PEATON,ERUM,NaN,1.0,PEDIATRICO DE COYOACAN,martes,10.0,MEDIA,NaN,"19.307892,-99.143964"
1,1,906166,2019-01-01,2019,Enero,7:39,LESIONADO,CHOQUE,-99.136425,19.470067,...,CONDUCTOR,ERUM,NaN,0.0,NaN,martes,7.0,BAJA,NaN,"19.470067,-99.136425"
2,2,906349,2019-01-01,2019,Enero,9:58,LESIONADO,CHOQUE,-99.069299,19.411029,...,CONDUCTOR,CRUZ ROJA,NaN,0.0,NaN,martes,9.0,BAJA,POSTE,"19.411029,-99.069299"
3,3,906469,2019-01-01,2019,Enero,11:35,LESIONADO,CHOQUE,-99.124262,19.470372,...,CONDUCTOR,CRUZ ROJA,NaN,1.0,ANGELES LINDAVISTA,martes,11.0,MEDIA,SEÑALAMIENTO,"19.470372,-99.124262"
4,4,907106,2019-01-01,2019,Enero,19:26,LESIONADO,CHOQUE,-98.996834,19.348251,...,CONDUCTOR,ERUM,NaN,0.0,NaN,martes,19.0,BAJA,NaN,"19.348251,-98.996834"

In [11]:
df_comparativa.dtypes

id                 int64
no_folio          object
fecha_evento      object
ano_evento         int64
mes               object
                  ...
dia               object
hora2            float64
prioridad         object
observaciones     object
coordenada        object
Length: 62, dtype: object

### Resumen variables numericas

In [8]:
df_no_comparativa.describe().T

,count,mean,std,min,25%,50%,75%,max
coordenada_x,110224.0,195.884269,58596.525938,19.061356,19.343246,19.393816,19.438470,1.945407e+07
coordenada_y,110227.0,-99.131523,0.847106,-99.999630,-99.172050,-99.138020,-99.098319,9.921877e+01
tipo_de_vehiculo_4,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
marca_de_vehiculo_4,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
se_desconoce_occiso,110231.0,0.002622,0.066417,0.000000,0.000000,0.000000,0.000000,1.000000e+01
se_desconoce_lesionado,110231.0,0.114904,0.390403,0.000000,0.000000,0.000000,0.000000,2.200000e+01
rango_de_edades_menores_de_1_ano_lesionado,110231.0,0.001043,0.032563,0.000000,0.000000,0.000000,0.000000,2.000000e+00
rango_edades_1_4_occiso,110231.0,0.000073,0.008519,0.000000,0.000000,0.000000,0.000000,1.000000e+00
rango_edades_1_4_lesionado,110231.0,0.009625,0.102972,0.000000,0.000000,0.000000,0.000000,3.000000e+00
rango_edades_5_14_occiso,110231.0,0.000263,0.021082,0.000000,0.000000,0.000000,0.000000,5.000000e+00
rango_edades_5_14_lesionado,110231.0,0.042556,0.225302,0.000000,0.000000,0.000000,0.000000,8.000000e+00
rango_edades_15_24_occiso,110231.0,0.002595,0.052968,0.000000,0.000000,0.000000,0.000000,3.000000e+00
rango_edades_15_24_lesionado,110231.0,0.257305,0.481604,0.000000,0.000000,0.000000,0.000000,6.000000e+00
rango_edades_25_34_occiso,110231.0,0.005525,0.076769,0.000000,0.000000,0.000000,0.000000,3.000000e+00
rango_edades_25_34_lesionado,110231.0,0.337918,0.520886,0.000000,0.000000,0.000000,1.000000,8.000000e+00
rango_edades_35_44_occiso,110231.0,0.004082,0.064470,0.000000,0.000000,0.000000,0.000000,2.000000e+00
rango_edades_35_44_lesionado,110231.0,0.185057,0.412629,0.000000,0.000000,0.000000,0.000000,6.000000e+00
rango_edades_45_64_occiso,110231.0,0.003556,0.060285,0.000000,0.000000,0.000000,0.000000,2.000000e+00
rango_edades_45_64_lesionado,110231.0,0.169072,0.414274,0.000000,0.000000,0.000000,0.000000,1.100000e+01
rango_edades_65_occiso,110231.0,0.001451,0.038071,0.000000,0.000000,0.000000,0.000000,1.000000e+00
rango_edades_65_lesionado,110231.0,0.044860,0.214362,0.000000,0.000000,0.000000,0.000000,4.000000e+00
total_occisos,110231.0,0.020167,0.153527,0.000000,0.000000,0.000000,0.000000,1.000000e+01
occisos_femeninos,110231.0,0.003629,0.061473,0.000000,0.000000,0.000000,0.000000,3.000000e+00
occisos_masculinos,110231.0,0.016175,0.130879,0.000000,0.000000,0.000000,0.000000,3.000000e+00
occiso_se_desconoce,110231.0,0.000363,0.039038,0.000000,0.000000,0.000000,0.000000,1.000000e+01
total_lesionados,110231.0,1.162332,0.626469,0.000000,1.000000,1.000000,1.000000,2.500000e+01
lesionados_femeninos,110231.0,0.346717,0.598009,0.000000,0.000000,0.000000,1.000000,1.500000e+01
lesionados_masculinos,110231.0,0.803594,0.571463,0.000000,0.000000,1.000000,1.000000,1.100000e+01
lesionado_se_desconoce,110231.0,0.012029,0.176965,0.000000,0.000000,0.000000,0.000000,2.200000e+01
hora2,110222.0,15249.730190,25277.015932,0.000000,10.000000,18.000000,28800.000000,8.280000e+04
zona_vial,110231.0,2.990801,1.430315,1.000000,2.000000,3.000000,4.000000,5.000000e+00
peaton_occiso,75188.0,0.005998,0.077389,0.000000,0.000000,0.000000,0.000000,2.000000e+00
peaton_lesionado,75188.0,0.160903,0.391114,0.000000,0.000000,0.000000,0.000000,6.000000e+00
ciclista_occiso,75188.0,0.000958,0.030930,0.000000,0.000000,0.000000,0.000000,1.000000e+00
ciclista_lesionado,75188.0,0.083165,0.282561,0.000000,0.000000,0.000000,0.000000,1.200000e+01
pasajero_occiso,75188.0,0.003046,0.059290,0.000000,0.000000,0.000000,0.000000,3.000000e+00
pasajero_lesionado,75188.0,0.218319,0.650581,0.000000,0.000000,0.000000,0.000000,2.500000e+01
motociclista_occiso,75188.0,0.006810,0.082239,0.000000,0.000000,0.000000,0.000000,1.000000e+00
motociclista_lesionado,75188.0,0.506504,0.513763,0.000000,0.000000,0.000000,1.000000,4.000000e+00
conductor_occiso,75188.0,0.002234,0.047498,0.000000,0.000000,0.000000,0.000000,2.000000e+00
conductor_lesionado,75188.0,0.191533,0.455601,0.000000,0.000000,0.000000,0.000000,7.000000e+00
rango_de_edades_menores_de_1_ano_occiso,58747.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00

In [9]:
df_comparativa.describe().T

,count,mean,std,min,25%,50%,75%,max
id,30758.0,15378.500000,8879.214126,0.000000,7689.25000,15378.500000,23067.750000,30757.000000
ano_evento,30758.0,2018.446388,0.497126,2018.000000,2018.00000,2018.000000,2019.000000,2019.000000
coordenada_x,30758.0,-99.140562,0.069885,-99.999630,-99.17560,-99.141451,-99.105318,-98.153068
coordenada_y,30758.0,19.392481,0.067229,18.893255,19.34681,19.398742,19.440424,19.963880
se_desconoce_occiso,30758.0,0.005787,0.107430,0.000000,0.00000,0.000000,0.000000,10.000000
se_desconoce_lesionado,30758.0,0.142044,0.436582,0.000000,0.00000,0.000000,0.000000,16.000000
rango_de_edades_menores_de_1_ano_occiso,30758.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
rango_de_edades_menores_de_1_ano_lesionado,30758.0,0.001691,0.041867,0.000000,0.00000,0.000000,0.000000,2.000000
rango_edades_1_4_occiso,30758.0,0.000065,0.008064,0.000000,0.00000,0.000000,0.000000,1.000000
rango_edades_1_4_lesionado,30758.0,0.011639,0.112870,0.000000,0.00000,0.000000,0.000000,3.000000
rango_edades_5_14_occiso,30758.0,0.000325,0.031230,0.000000,0.00000,0.000000,0.000000,5.000000
rango_edades_5_14_lesionado,30758.0,0.048800,0.242436,0.000000,0.00000,0.000000,0.000000,4.000000
rango_edades_15_24_occiso,30758.0,0.002764,0.054919,0.000000,0.00000,0.000000,0.000000,3.000000
rango_edades_15_24_lesionado,30758.0,0.245595,0.471952,0.000000,0.00000,0.000000,0.000000,6.000000
rango_edades_25_34_occiso,30758.0,0.005560,0.076085,0.000000,0.00000,0.000000,0.000000,2.000000
rango_edades_25_34_lesionado,30758.0,0.309676,0.507298,0.000000,0.00000,0.000000,1.000000,8.000000
rango_edades_35_44_occiso,30758.0,0.004324,0.065616,0.000000,0.00000,0.000000,0.000000,1.000000
rango_edades_35_44_lesionado,30758.0,0.177710,0.405871,0.000000,0.00000,0.000000,0.000000,5.000000
rango_edades_45_64_occiso,30758.0,0.004422,0.067322,0.000000,0.00000,0.000000,0.000000,2.000000
rango_edades_45_64_lesionado,30758.0,0.174069,0.414252,0.000000,0.00000,0.000000,0.000000,6.000000
rango_edades_65_occiso,30758.0,0.002471,0.049648,0.000000,0.00000,0.000000,0.000000,1.000000
rango_edades_65_lesionado,30758.0,0.052929,0.231183,0.000000,0.00000,0.000000,0.000000,4.000000
total_occisos,30758.0,0.025717,0.182345,0.000000,0.00000,0.000000,0.000000,10.000000
occisos_femeninos,30758.0,0.005137,0.074167,0.000000,0.00000,0.000000,0.000000,3.000000
occisos_masculinos,30758.0,0.019605,0.144158,0.000000,0.00000,0.000000,0.000000,3.000000
occiso_se_desconoce,30758.0,0.000975,0.070292,0.000000,0.00000,0.000000,0.000000,10.000000
total_lesionados,30758.0,1.164152,0.641677,0.000000,1.00000,1.000000,1.000000,20.000000
lesionados_femeninos,30758.0,0.362052,0.613230,0.000000,0.00000,0.000000,1.000000,11.000000
lesionados_masculinos,30758.0,0.781943,0.578705,0.000000,0.00000,1.000000,1.000000,9.000000
lesionado_se_desconoce,30758.0,0.020157,0.217089,0.000000,0.00000,0.000000,0.000000,12.000000
trasladado_s_lesionado,30758.0,0.328175,0.586875,0.000000,0.00000,0.000000,1.000000,26.000000
hora2,30750.0,12.572780,6.239031,0.000000,8.00000,13.000000,18.000000,23.000000

In [12]:
##no hay columna  año en el DataFrame no_comparativo asi que lo vamos a extraer y convertir a int para que coincida con el otr CVS
df_no_comparativa['ano_evento'] = pd.to_datetime(df_no_comparativa["fecha_evento"]).dt.year

In [13]:
df_no_comparativa.ano_evento.unique()

array([2020, 2019, 2018, 2021, 2022, 2023], dtype=int32)

In [14]:
###tambien en la columna hora2 hay un error de horas inexistentes como 80000 hrs
## por lo que extraeremos  la hora2 de la columna hora
df_no_comparativa['hora2'] = pd.to_datetime(df_no_comparativa['hora'], format='%H:%M:%S').dt.hour

#### Extrar columnas que se comparten en ambos CSV

In [15]:
##checamos las columnas compartidas que  
columns_comparativa=list(df_comparativa.columns)
columns_no_comparativa=list(df_no_comparativa.columns)
columnas_compartidas=[x for x in columns_comparativa if x in columns_no_comparativa]

In [16]:
# seleccionamos columnas comunes entre ambos DataFrames
df_comparativa_s=df_comparativa[columnas_compartidas]
df_no_comparativa_s=df_no_comparativa[columnas_compartidas]
##comprobamos que ahora si tengan el mismo numero de columnas
print(df_comparativa_s.shape)
print(df_no_comparativa_s.shape)

(30758, 61)
(110231, 61)

### Eliminamos los años 2018-2019 de la tabla no comparativa y unimos

In [18]:
###eliminamos los años 2018 y 2019 de la DF no comparativa por que son los que tienen errores
## lo anterior para para hacer un merge de las dos tablas 
df_no_comparativa_s=df_no_comparativa_s[df_no_comparativa_s["ano_evento"] > 2019]
df_no_comparativa_s.ano_evento.unique()

array([2020, 2021, 2022, 2023], dtype=int32)

In [19]:
## concatenamos
transito_concat=pd.concat([df_comparativa_s,df_no_comparativa_s], ignore_index=True)

In [20]:
transito_concat

,no_folio,fecha_evento,ano_evento,mes,hora,condicion,tipo_de_evento,coordenada_x,coordenada_y,punto_1,...,identidad,unidad_medica_de_apoyo,lugar_del_deceso,trasladado_s_lesionado,hospital,dia,hora2,prioridad,observaciones,coordenada
0,906379,2019-01-01,2019,Enero,10:13,LESIONADO,ATROPELLADO,-99.143964,19.307892,HIDALGO,...,PEATON,ERUM,NaN,1.0,PEDIATRICO DE COYOACAN,martes,10.0,MEDIA,NaN,"19.307892,-99.143964"
1,906166,2019-01-01,2019,Enero,7:39,LESIONADO,CHOQUE,-99.136425,19.470067,EJE CENTRAL,...,CONDUCTOR,ERUM,NaN,0.0,NaN,martes,7.0,BAJA,NaN,"19.470067,-99.136425"
2,906349,2019-01-01,2019,Enero,9:58,LESIONADO,CHOQUE,-99.069299,19.411029,EJE 5 PTE,...,CONDUCTOR,CRUZ ROJA,NaN,0.0,NaN,martes,9.0,BAJA,POSTE,"19.411029,-99.069299"
3,906469,2019-01-01,2019,Enero,11:35,LESIONADO,CHOQUE,-99.124262,19.470372,AV BASILIO ROMO ANGUIANO,...,CONDUCTOR,CRUZ ROJA,NaN,1.0,ANGELES LINDAVISTA,martes,11.0,MEDIA,SEÑALAMIENTO,"19.470372,-99.124262"
4,907106,2019-01-01,2019,Enero,19:26,LESIONADO,CHOQUE,-98.996834,19.348251,15 DE SEPTIEMBRE,...,CONDUCTOR,ERUM,NaN,0.0,NaN,martes,19.0,BAJA,NaN,"19.348251,-98.996834"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105941,C5/20230131/02528,2023-01-31,2023,enero,17:39:00,NaN,DERRAPADO,19.241998,-99.167356,CARR FED MEXICO CUERNAVACA,...,NaN,ERUM,NaN,SI,NaN,martes,17.0,MEDIA,NaN,NaN
105942,C5/20230131/03152,2023-01-31,2023,enero,20:28:00,NaN,DERRAPADO,19.414197,-99.163335,EJE 2 SUR,...,NaN,ERUM,NaN,NO,NaN,martes,20.0,BAJA,NaN,NaN
105943,C2P/20230131/00157,2023-01-31,2023,enero,22:03:00,NaN,DERRAPADO,19.488520,-99.201540,GRAL FCO SARABIA,...,NaN,ERUM,NaN,NO,NaN,martes,22.0,BAJA,NaN,NaN
105944,C5/20230131/03678,2023-01-31,2023,enero,22:59:00,NaN,DERRAPADO,19.497703,-99.165476,EJE 5 NTE,...,NaN,ERUM,NaN,NO,NaN,martes,22.0,BAJA,NaN,NaN
105945,C5/20230131/02248,2023-01-31,2023,enero,16:18:00,NaN,VOLCADURA,19.248127,-99.172363,CARR FED MEXICO CUERNAVACA,...,NaN,MOTO ERUM,NaN,NO,NaN,sábado,16.0,BAJA,NaN,NaN

In [21]:
#corroboramos que coinciden con la suma de las DataFrames originales 
print(transito_concat.shape[0])
print(df_no_comparativa_s.shape[0] + df_comparativa_s.shape[0])

105946
105946

### Seleccion de variables

In [22]:
transito_concat_a=transito_concat[["fecha_evento",	"ano_evento","mes","dia","hora2","condicion","tipo_de_evento","colonia","alcaldia","tipo_de_interseccion","tipo_de_vehiculo_1","tipo_de_vehiculo_2",
"lesiones","edad_lesionado","identidad","unidad_medica_de_apoyo","total_lesionados","total_occisos"]]

In [23]:
transito_concat_a.shape

(105946, 18)

Vamos a checar las demas columnas para ver si requieren algun tipo de tratamiento

In [24]:
##haremos un loop para guardar todos  los valores unicos de cada columna 
#en un diccionario  y depues poder consultar cada uno de estos  
valores_unicos=[]
for i in transito_concat_a.columns:
  valores_unicos.append(transito_concat_a[i].unique())

In [30]:
valores_unicos={}
for i in transito_concat_a.columns:
  valores_unicos[i]=transito_concat_a[i].unique()

In [34]:
valores_unicos['fecha_evento']

array(['2019-01-01', '2019-01-02', '2019-01-03', ..., '2023-01-29',
       '2023-01-30', '2023-01-31'], dtype=object)

#### Es necesario corregir las columna 2, 3 y 9

In [35]:
### corregir el mes ya que algunos estan mayusculas y otros no 
transito_concat_a['mes']=transito_concat_a['mes'].apply(str.lower)

/tmp/ipykernel_65326/1822744210.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transito_concat_a['mes']=transito_concat_a['mes'].apply(str.lower)

In [36]:
# En el dia hay unos en mayusculas y otros no, y ademas hay valores con erroes 
transito_concat_a['dia']=transito_concat_a['dia'].apply(str.lower)

/tmp/ipykernel_65326/1506380450.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transito_concat_a['dia']=transito_concat_a['dia'].apply(str.lower)

In [37]:
##checamos los errores 
transito_concat_a["dia"].unique()

array(['martes', 'miércoles', 'jueves', 'viernes', 'sábado', 'domingo',
       'lunes', 'coruña', 'miérco', 'siérco', 'taxqueñes',
       'calz taxqueña', 'ruben leñero', 'taxqueña', 'mábado', 's<c3>érco',
       '1° de mayo', 'sabado', 'miercoles'], dtype=object)

In [38]:
#remplazamos  
transito_concat_a=transito_concat_a.replace(to_replace=["miércoles",'miérco', 'mábado','sábado'],value=['miercoles','miercoles',"sabado","sabado"])

In [40]:
## hay filas con otros valores que no son dias 
## En este caso repmplazaremos eso valors con la moda   
transito_concat_a["dia"].mode()[0]

'sabado'

In [41]:
transito_concat_a=transito_concat_a.replace(['coruña', 'siérco', 'taxqueñes', 'calz taxqueña',
       'ruben leñero', 'taxqueña', 's<c3>érco', '1° de mayo'],"sabado")

In [42]:
# checamos
transito_concat_a["dia"].unique()

array(['martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo',
       'lunes'], dtype=object)

In [43]:
## Ahora vamos con el tipo de interseccion 
#en estre caso utilizaremos mayusculas para homologar
transito_concat_a.tipo_de_interseccion.unique()

array(['T', 'Y', 'CRUZ', 'RECTA', 'RAMAS MULTIPLES', 'DESNIVEL',
       'GLORIETA', 'GAZA', 'CURVA', 'y', 't', 'RECTA DESNIVEL',
       'CARRILES LATERALES'], dtype=object)

In [44]:
##remlazamos minusculas por mayusculas 
transito_concat_a.replace(to_replace=['y', 't'],value=['T', 'Y'], inplace=True)

In [45]:
##checamos
transito_concat_a.tipo_de_interseccion.unique()

array(['T', 'Y', 'CRUZ', 'RECTA', 'RAMAS MULTIPLES', 'DESNIVEL',
       'GLORIETA', 'GAZA', 'CURVA', 'RECTA DESNIVEL',
       'CARRILES LATERALES'], dtype=object)

### Guardamos en formato csv la DataFrame Unida para los análisis

In [46]:
transito_concat_a.to_csv('./data/Hechos_transito_concat.csv', index=None)